# NUMPY  / Numerical Python

In [ ]:
import numpy as np #lo llamamos np

Importar Libreria

In [ ]:
import numpy as np #lo llamamos np

Caracteristicas


1. Se pueden utilizar para modelos de IA
2. Reconocimiento de imagenes (usan tensores)
3. No podemos guardar diferentes datos en un array
4. Numpy fuerza y lo convierte en un tipo


## Crear arrays basicos

In [ ]:
arrya_t=np.array([1,"palabra"])

npa=np.array(range(10))

print(arrya_t) # me los transforma en string


['1' 'palabra']



 1 DIMENSION

In [ ]:
vector=np.array([1,2])
print(vector)

[1 2]


 DIMENSIONES

In [ ]:
# 2 CORCHETES (2 AL INICIO Y 2 AL FINAL
matriz=np.array ([[1,2],[3,4]])
print(matriz)

[[1 2]
 [3 4]]


3 DIMENSIONES

In [ ]:
#3 CORCHETES

TENSOR=np.array([[[1,2],[2,1]],
                 [[1,2],[2,1]],
                 [[1,2],[2,1]]])

print(TENSOR)

[[[1 2]
  [2 1]]

 [[1 2]
  [2 1]]

 [[1 2]
  [2 1]]]


## Crear arreglos automaticos

In [ ]:
np_ceros=np.zeros(10) #tipo decimal o float

np_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np_uno=np.ones(10)
np_uno


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np_vector=np.full(10,34.3)
np_vector

array([34.3, 34.3, 34.3, 34.3, 34.3, 34.3, 34.3, 34.3, 34.3, 34.3])

In [ ]:
np_matriz=np.full((2,3),[1,2,2])  #(filas,columnas) (valores filas c/u c1,c2,c3 en este ejemplo)
np_matriz

array([[1, 2, 2],
       [1, 2, 2]])

In [ ]:
np_tensor=np.full((2,2,3),[1,2,2])  #(matriz,filas,columnas) (valores filas c/u c1,c2,c3 en este ejemplo)
np_tensor

array([[[1, 2, 2],
        [1, 2, 2]],

       [[1, 2, 2],
        [1, 2, 2]]])

In [ ]:
np_rango=np.arange(1,100,5)  # (Punto partida,pto final,de cuanto en cuanto)
np_rango

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [ ]:
#numeros aleatorios

np_random=np.random.randint(low=0,high=10,size=(2,6,3)) #matrices,filas, columnas
np_random

array([[[7, 2, 1],
        [5, 2, 4],
        [1, 5, 1],
        [4, 7, 8],
        [6, 2, 5],
        [9, 3, 9]],

       [[1, 3, 3],
        [5, 0, 8],
        [9, 0, 4],
        [4, 1, 4],
        [2, 9, 1],
        [8, 6, 6]]])

## Tipos de datos de arrays

In [ ]:
arr1 = np.array([True, False, True, False])
print(arr1.dtype)

bool


In [ ]:
arr4 = np.array([1, 2, 3, 4], dtype='U') #aca obligo a que estos numeros se vuelvan string o cadena de caracteres

print(arr4)
print(arr4.dtype)

['1' '2' '3' '4']
<U1


In [ ]:
#**También podemos convertir los tipos de datos del array despues de creado**

arr = np.array([1.1, 2.1, 3.1]) #inicialmente tiene tipo float o decimal

newarr = arr.astype('i')  #aca le cambiamos el tipo a entero (int) y creamos un nuevo array

print("inicialmente:",arr,arr.dtype)
print("")
print("despues de cambiado el tipo:",newarr,newarr.dtype)

inicialmente: [1.1 2.1 3.1] float64

despues de cambiado el tipo: [1 2 3] int32


##Atributos de datos de arrays




# Sección nueva

In [ ]:
#Creamos un array
matriz=np.array([[1,2,2],
                 [3,4,2]])
matriz

array([[1, 2, 2],
       [3, 4, 2]])

In [ ]:
matriz.ndim # Te dice la cantidad dimensiones(vector,matriz,tensor, etc)

2

array.shape: Para saber numero de dimensiones, numero de arrays que tenemos y filas y columnas dentro de cada array

Por ejemplo:

* (2,) = 1 vector (1D) con 2 elementos por dentro
* (2,2) = 1 matriz (2D) con 2 filas y 2 columnas
* (3,2,2) = 1 tensor (3D) con 3 matrices de 2 filas y 2 columnas




In [ ]:
shape=matriz.shape
shape

(2, 3)

In [ ]:
#.size ---- cantidad de elementos
matriz.size

6

##Accedo a elementos

In [ ]:
#usando posicion vector

np_diez_numeros = np.arange(1,11) #me crea numeros del 1 al 10
np_diez_numeros

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np_diez_numeros[8]

9

In [ ]:
#matriz
matriz_nueva=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
matriz_nueva

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
matriz_nueva[1][2] #Fila, columna

7

In [ ]:
tensor=np.array([[[1,2],
                  [3,4]],

                 [[5,6],
                  [7,8]],

                 [[9,10],
                  [11,12]]])
tensor

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
tensor[1:,0:,0] #matriz,Fila, columna

array([[ 5,  7],
       [ 9, 11]])

## SUBARRAYS

Seleccionar "rebanadas" de nuestros arrays.

Utilizamos los **indices** o la posicion del elemento dentro del array.

Estructura: **array[ desde : hasta_antes_de : tamaño_de_paso]**

In [ ]:
tensor_nuevo=np.array([[[1,2,12],[3,4,34]],
                 [[5,6,56],[7,8,78]],
                 [[9,10,910],[11,12,1112]]])
tensor_nuevo

array([[[   1,    2,   12],
        [   3,    4,   34]],

       [[   5,    6,   56],
        [   7,    8,   78]],

       [[   9,   10,  910],
        [  11,   12, 1112]]])

In [ ]:
tensor_nuevo[0:][0:][2]

array([[   9,   10,  910],
       [  11,   12, 1112]])

In [ ]:
np.where(tensor_nuevo==9)

(array([2]), array([0]), array([0]))

## OPERACIONES BASICAS EN ARRAYS

###Reshape

In [ ]:
# pasar de  8 filas y 8 columnas (8x8)
# A 1X64

arraya=np.arange(1,65)
arraya

modificado=arraya.reshape(8,1,8)
modificado



array([[[ 1,  2,  3,  4,  5,  6,  7,  8]],

       [[ 9, 10, 11, 12, 13, 14, 15, 16]],

       [[17, 18, 19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30, 31, 32]],

       [[33, 34, 35, 36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45, 46, 47, 48]],

       [[49, 50, 51, 52, 53, 54, 55, 56]],

       [[57, 58, 59, 60, 61, 62, 63, 64]]])

###CONCATENAR - FUNCION CONCATENATE

Juntar arreglos, tienen que tener la misma deimensiones

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[7,8]])

print("primer array")
print(a)
print("")
print("segundo array")
print(b)

primer array
[[1 2]
 [3 4]]

segundo array
[[5 6]
 [7 8]]


In [ ]:
np.concatenate((a,b), axis=0) #axis=o significa unir filas de mis arrays

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((a,b), axis=1) #axis=o significa unir columnas de mis arrays

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

###CONCATENATE - VSTACK / HSTACK

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6],[7,8]])

print("primer array")
print(a)
print("")
print("segundo array")
print(b)

primer array
[[1 2]
 [3 4]]

segundo array
[[5 6]
 [7 8]]


In [ ]:
Array_apilados_h = np.hstack([a, b])
Array_apilados_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
Array_apilados_V = np.vstack([a, b])
Array_apilados_V

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### SPLIT

Consiste en desarmar o partir los arreglos.
Puede pensarse como la operación inversa a la concatenación.
Las siguientes funciones nos ayudan con esto:

In [ ]:
n_array = np.array([1,2,10,20,40,60])

print(n_array)

[ 1  2 10 20 40 60]


In [ ]:
A1,A2,A3=np.split(n_array,[2,4],axis=0)  #aca le digo que lo divida en 3 partes: hasta antes del indice 2, desde el 2 hasta antes del 4 y desde el indice 4

print (A1)
print (A2)
print (A3)

[1 2]
[10 20]
[40 60]


In [ ]:
narray = np.array([[1,2,10,20,40,60],
                   [100,200,1000,2000,4000,6000],
                   [1,2,10,20,40,60],
                   [100,200,1000,2000,4000,6000]])

print(narray)
print("")


narray1,narray2,narray3= np.split(narray,[2,4],axis=0)  #me crea 3 arrays

print(narray1)
print(" espacio ")
print(narray2)
print(" espacio ")
print(narray3)

[[   1    2   10   20   40   60]
 [ 100  200 1000 2000 4000 6000]
 [   1    2   10   20   40   60]
 [ 100  200 1000 2000 4000 6000]]

[[   1    2   10   20   40   60]
 [ 100  200 1000 2000 4000 6000]]
 espacio 
[[   1    2   10   20   40   60]
 [ 100  200 1000 2000 4000 6000]]
 espacio 
[]


HSPLIT

In [ ]:
n_array = np.array([[1,2,10,20,40,60],
                    [100,200,1000,2000,4000,6000],
                    [150,250,1050,2050,4050,6050]])

print(n_array) #tengo un array que es una matriz de 3 filas y 6 columnas

[[   1    2   10   20   40   60]
 [ 100  200 1000 2000 4000 6000]
 [ 150  250 1050 2050 4050 6050]]


In [ ]:
na1,na2,na3=np.hsplit(n_array, 3)  #me quedan 3 arrays cada uno es una matriz de 3 filas y 2 columnas
print(na1)
print(na2)
print(na3)

[[  1   2]
 [100 200]
 [150 250]]
[[  10   20]
 [1000 2000]
 [1050 2050]]
[[  40   60]
 [4000 6000]
 [4050 6050]]


VSPLIT

In [ ]:
narray = np.array([[1,2,10,20,40,60],
                   [100,200,1000,2000,4000,6000],
                   [150,250,1050,2050,4050,6050]])

print(narray) #tengo un array que es una matriz de 3 filas y 6 columnas

[[   1    2   10   20   40   60]
 [ 100  200 1000 2000 4000 6000]
 [ 150  250 1050 2050 4050 6050]]


In [ ]:
np.vsplit(narray,3) #me quedan 3 arrays cada uno de 1 fila y 6 columnas

[array([[ 1,  2, 10, 20, 40, 60]]),
 array([[ 100,  200, 1000, 2000, 4000, 6000]]),
 array([[ 150,  250, 1050, 2050, 4050, 6050]])]

## AGREGACIONES

UTILIZO UN FOR PARA CALCULAR PROMEDIO

In [ ]:
Array_al = np.array([7,4,7,8,3,1,7,4,0,6])

suma = 0
cantidad_elementos=0

for i in Array_al:
  suma += i
  cantidad_elementos+=1

promedio = suma/ cantidad_elementos

print("suma de todos los elementos:",suma)
print("cantidad de elementos",np.size(Array_al))
print("promedio",promedio)

suma de todos los elementos: 47
cantidad de elementos 10
promedio 4.7


UTILIZO AGREGACION PARA CALCULAR PROMEDIO

In [ ]:
Array_al.sum() #suma de todos los elementos del array

47

In [ ]:
Array_al.mean() #promedio de los elementos del array

4.7

In [ ]:
Array_al.max() #valor mas alto del array

8

In [ ]:
Array_al.min() #valor mas alto del array

0

## UFUNCS

Las operaciones vectorizadas o funciones universales (ufuncs) nos permiten operar entre arreglos de la manera más rápida posible.


In [ ]:
Array_al = np.array([7,4,7,8,3,1,7,4,0,6])

Array_al2 = np.array([1,1,1,1,1,1,1,1,1,1])

In [ ]:
Array_al + 10

array([17, 14, 17, 18, 13, 11, 17, 14, 10, 16])

In [ ]:
np.add(Array_al, Array_al2)

array([8, 5, 8, 9, 4, 2, 8, 5, 1, 7])

# PRACTICA

In [ ]:
tensor_x=np.array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

        [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]]])


In [ ]:
print("¿Cúantas dimensiones tiene ese tensor?")

tensor_x.ndim




¿Cúantas dimensiones tiene ese tensor?


3

In [ ]:
tensor_x.shape


(5, 3, 3)

In [ ]:
tensor_x.size

45

* ¿Cúantas dimensiones tiene ese tensor?

* ¿Cuántas matrices tiene ese tensor?

* ¿Qué tamaño tienen las matrices? (Filas x Columnas)

* ¿Cuántos elementos hay en total?

In [15]:
"""
[[1.1. 1. 1. 1.]
[1.0. 0. 0. 1.]
[1.0. 9. 0. 1.]
[1.0. 0. 0. 1.]
[1.1. 1. 1. 1.]]
"""

import numpy as np

output=np.ones((5,5))
print(output)
print("\n")

z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z

print(z)
print("\n")
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
objetivo=np.array([
    [0., 0., 0., 0., 0., 0., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 1., 1., 5., 1., 1., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 1., 1., 1., 1., 1., 0.],
    [0., 0., 0., 0., 0., 0., 0.]
])

shapeobj=np.shape(objetivo)

output1=np.zeros(shapeobj)
matrizinterna=np.ones((5,5))
matrizinterna[2,2]=5

output1[1:6,1:6]=matrizinterna

output1

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [41]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=0)
b

array([ 6,  7,  8,  9, 10])

In [ ]:
before=np.array ([[1,2,3,4],[5,6,7,8]])